### ISSUE TITLE
Rename "17.01" to something like "16.02.1"

### ISSUE THREAD

**Issue by ipaucek4680** [szcnick/p7zip#18]
This fork's "17.00" and "17.01" releases are not based on 7-Zip 17.00/17.01.
To avoid confusion, please consider naming the release to something like "16.02.1" to indicate the **actual 7-Zip version** that the release is based on.
Using another naming scheme, such as using the release date as the version name (e.g. version 2020.05.13), would also be a good idea.
<hr>
这个分支所发布的 "17.00" 和 "17.01" 版本并非基于 7-Zip 17.00/17.01。<br />
为免误会，请考虑将版本号重命名为 "16.02.1" 之类的，以反映其<b>实际对应之 7-Zip 版本</b>。<br />
采用另一种命名办法，例如以版本发布日期作为版本号（例如 2020.05.13），也是一种好方法。

**Comment by jinfeihan57** [comment]
It takes a long time to update the version, but the bugs that have been found are more urgent. So fix the bug first. Other features of the version will be updated later. You can check it by the link below. As for the version number, I haven't named it exactly after 7zip. More new features will be updated in the future.Eventually we will make p7zip and 7zip have the same version 19.00.
Check this link: https://github.com/szcnick/p7zip/commit/846633b7a9ec7f3f53027f6695dcc39b0af47bbd

版本更新比较耗时，但是已经发现的漏洞比较紧急。所以先更新了漏洞。随后会更新版本的其他特性。你可以查看上面的链接获取，至于版本号现阶段我没有完全按照7zip的命名。后续会有更多的新特性更新进来。最终我们会在19.00版本与7zip保持一致。

**Comment by jinfeihan57** [comment]
I released [p7zip 17.02](https://github.com/szcnick/p7zip/releases).it was developed on the basis of [7zip17.01](https://sourceforge.net/projects/sevenzip/files/7-Zip/17.01/) and added some new features of [7zip-zstd](https://github.com/mcmilk/7-Zip-zstd)， and fixed some bugs of p7zip16.02.

**Comment by ipaucek4680** [comment]
Thank you very much.

**Comment by jinfeihan57** [comment]
@ipaucek4680 
You speak Chinese？

**Comment by ipaucek4680** [comment]
@jinfeihan57 
Yeah, I can speak Chinese.
