### ISSUE TITLE
Question regarding project name

### ISSUE THREAD

**Issue by antermin** [szcnick/p7zip#193]
I noticed that this project has been renamed to p7zip-zstd in README.

Meanwhile, in [this comment](https://sourceforge.net/p/sevenzip/feature-requests/1580/?limit=25#f045), Igor Pavlov reveals that he is working on Zstd support in 7-Zip. We don't know whether his version will maintain compatibility with Zstd 7z archives created by unofficial forks.

Do you have any plan to rename the project again when a new version of upstream 7-Zip with Zstd support is released?
This fork can still offer additional codecs other than Zstd (Brotli, Fast LZMA2, LZ4, LZ5, Lizard, Lzham), and integrate community patches / features which are not included by upstream.

**Comment by jinfeihan57** [comment]
The name is related to [7zip-zstd](https://github.com/mcmilk/7-Zip-zstd/). I noticed that Igor Pavlov is working on Zstd support in 7-Zip. And I hope his version will compatibility with this project. The name has not been finalized yet, but it is first used in readme. It may change in the future according to the development of 7zip and 7zip-zstd.
