### ISSUE TITLE
Update zstd codec to 1.4.5

### ISSUE THREAD

**Issue by gdluca** [szcnick/p7zip#24]
Hello,
At work, I use a lot of 7z files with zstd so thank you for creating this fork.
When you have time, please update zstd codec to the latest 1.4.5 which it improves a little the compression ratio.

**Comment by jinfeihan57** [comment]
I will do it next week. it is in my plan now.  ;-)

**Comment by jinfeihan57** [comment]
@gdluca 
check this PR #26.

**Comment by gdluca** [comment]
Thanks!

**Comment by ipaucek4680** [comment]
Will there be a new tagged release for the updated Zstd version? Thanks!

**Comment by jinfeihan57** [comment]
NO！I am planning to release a new version of p7zip, so it will not be released separately for zstd 1.4.5.
