### ISSUE TITLE
Port upstream fix for mcmilk/7-Zip-zstd#131

### ISSUE THREAD

**Issue by ipaucek4680** [szcnick/p7zip#27]
p7zip may also have the same issue as mcmilk/7-Zip-zstd#131 and therefore mcmilk/7-Zip-zstd@9378903 and mcmilk/7-Zip-zstd@256e464 may need to be ported to p7zip.

**Comment by ipaucek4680** [comment]
Update:
Upstream has bug fixes for other issues like mcmilk/7-Zip-zstd#133 and mcmilk/7-Zip-zstd#130, so maybe it's time to sync the related code.

**Comment by jinfeihan57** [comment]
[ mcmilk/7-Zip-zstd#130](https://github.com/mcmilk/7-Zip-zstd/issues/130) p7zip don't have it(I added judgment when porting zstd ). 
 [mcmilk/7-Zip-zstd#133](https://github.com/mcmilk/7-Zip-zstd/issues/133) I think this is a GUI bug. p7zip has no GUI yet. so it not a problem.
You can verify them.Please feedback me in time for any problems. 
[ mcmilk/7-Zip-zstd#131](https://github.com/mcmilk/7-Zip-zstd/issues/131) I will look at it.

**Comment by jinfeihan57** [comment]
[mcmilk/7-Zip-zstd#131](https://github.com/mcmilk/7-Zip-zstd/issues/131) It was fixed. #29

**Comment by ipaucek4680** [comment]
Thanks for the fix.

May I ask a question? I am trying to set the parameters but it won't let me. Am I using the correct syntax?
`./7z a -m0=zstd test.7z ../CPP`: OK
`./7z a -m0=zstd:strategy=2 test-st2.7z ../CPP`: Error
`./7z a -m0=zstd:long test-long.7z ../CPP`: Error
`./7z a -m0=zstd:WindowLog=10 test-wlog.7z ../CPP`: Error

**Comment by jinfeihan57** [comment]
Old version zstd only support compression level setting.
The latest update supports the parameter setting of zstd. #33 
if you want set more parameters please download the latest dev branch.

**Comment by jinfeihan57** [comment]
One more thing next time when you have issue or bug, please open a issue or at least reopen it. 
Thanks!

**Comment by jinfeihan57** [comment]
ZSTD parameters NEW name:
strategy          ->    strat
fast                 ->    fast
long                ->    long
WindowLog    ->    wlog
HashLog         ->    hlog
ChainLog        ->    clog
SearchLog       ->   slog
MinMatch       ->    slen
TargetLen        ->    tlen
OverlapLog     ->    ovlog
LdmHashLog   ->    ldmhlog
LdmSearchLength  ->     ldmslen
LdmBucketSizeLog ->     ldmblog
LdmHashRateLog   ->     ldmhevery

One more thing next time when you have issue or bug, please open a issue or at least reopen it.
Thanks!

**Comment by ipaucek4680** [comment]
> One more thing next time when you have issue or bug, please open a issue or at least reopen it.
OK and sorry about that.
