### ISSUE TITLE
Squashfs with Zstd compression

### ISSUE THREAD

**Issue by babam86** [szcnick/p7zip#46]
Add support to open squashfs file with zstd compression.

Thanks.

**Comment by ipaucek4680** [comment]
Reference: mcmilk/7-Zip-zstd@35771b5

**Comment by jinfeihan57** [comment]
p7zip only support squashfs Decompress. Do you have any squashfs file that compressed by zstd or lz4 please upload it. Thanks!

**Comment by ipaucek4680** [comment]
The following ZIP file contains a squashfs image with Zstd compression (`-comp zstd -Xcompression-level 3`). I downloaded https://github.com/szcnick/p7zip/archive/dev.zip and re-compressed the folder using `mksquashfs`.

[p7zip-dev-squashfs.zip](https://github.com/szcnick/p7zip/files/4785633/p7zip-dev-squashfs.zip)

**Comment by jinfeihan57** [comment]
How does your mksquashfs support zstd, my mksquashfs only supports gzip, lzma, lzo, lz4 and xz. 
-Xcompression-level only work for gzip.
mksquashfs -Xhelp
![image](https://user-images.githubusercontent.com/38484902/84769816-0dbe7000-b009-11ea-9c2c-2c9a0c72060f.png)

**Comment by ipaucek4680** [comment]
@jinfeihan57 
Perhaps the `squashfs-tools` package you are using does not have `ZSTD_SUPPORT=1` configured. In that case, you will have to re-compile the `squashfs-tools` package.

For example, Arch Linux's `squashfs-tools` package is compiled with `ZSTD_SUPPORT=1`:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/squashfs-tools

**Comment by jinfeihan57** [comment]
[add lz4 and zstd](https://github.com/szcnick/p7zip/commit/2b98381787f4a3b67cc9f5243928fa8466c3c732)

**Comment by jinfeihan57** [comment]
[added lz4 and zstd method to squashfs](https://github.com/szcnick/p7zip/commit/2b98381787f4a3b67cc9f5243928fa8466c3c732)

**Comment by babam86** [comment]
Thank you very much.
