### ISSUE TITLE
7z extract symlinks contained inside squashfs as regular files

### ISSUE THREAD

**Issue by babam86** [szcnick/p7zip#47]
Similar problems such as https://github.com/szcnick/p7zip/issues/39

symlinks contained inside squashfs can't decompress correctly.

Thanks.

**Comment by jinfeihan57** [comment]
Please upload some example of such squashfs file.

**Comment by ipaucek4680** [comment]
[p7zip-dev-test-symlink.squashfs.zip](https://github.com/szcnick/p7zip/files/4791904/p7zip-dev-test-symlink.squashfs.zip)

**Comment by jinfeihan57** [comment]
It be [fixed] (https://github.com/szcnick/p7zip/commit/c820b5f678a44086b6ac740911842c1609b911c7) now.

**Comment by jinfeihan57** [comment]
It be [fixed](https://github.com/szcnick/p7zip/commit/c820b5f678a44086b6ac740911842c1609b911c7) now.

**Comment by babam86** [comment]
Thank you very much.
