### ISSUE TITLE
p7zip-17.02  -> make -j 4 test_7zr -> error

### ISSUE THREAD

**Issue by teoberi** [szcnick/p7zip#52]
`cp makefile.linux_amd64 makefile.machine`
`make -j 4 test_7zr`

> /usr/bin/ld: XzHandler.o: in function `NArchive::NXz::CHandler::Close()':
XzHandler.cpp:(.text+0x132): undefined reference to `NCompress::NXz::CStatInfo::Clear()'
/usr/bin/ld: XzHandler.o: in function `NArchive::NXz::CHandler::Extract(unsigned int const*, unsigned int, int, IArchiveExtractCallback*)':
XzHandler.cpp:(.text+0x8b3): undefined reference to `NCompress::NXz::CStatInfo::Clear()'
/usr/bin/ld: XzHandler.cpp:(.text+0x8bd): undefined reference to `NCompress::NXz::CXzUnpackerCPP::CXzUnpackerCPP()'
/usr/bin/ld: XzHandler.cpp:(.text+0x8ed): undefined reference to `NCompress::NXz::CDecoder::Decode(ISequentialInStream*, ISequentialOutStream*, unsigned long long const*, bool, ICompressProgressInfo*)'
/usr/bin/ld: XzHandler.cpp:(.text+0x941): undefined reference to `NCompress::NXz::CDecoder::Get_Extract_OperationResult() const'
/usr/bin/ld: XzHandler.cpp:(.text+0x973): undefined reference to `NCompress::NXz::CXzUnpackerCPP::~CXzUnpackerCPP()'
/usr/bin/ld: XzHandler.cpp:(.text+0xa2e): undefined reference to `NCompress::NXz::CXzUnpackerCPP::~CXzUnpackerCPP()'
/usr/bin/ld: XzHandler.o: in function `NArchive::NXz::CHandler::UpdateItems(ISequentialOutStream*, unsigned int, IArchiveUpdateCallback*)':
XzHandler.cpp:(.text+0xbdb): undefined reference to `NCompress::NXz::CEncoder::CEncoder()'
/usr/bin/ld: XzHandler.cpp:(.text+0xc42): undefined reference to `NCompress::NXz::CEncoder::SetCheckSize(unsigned int)'
/usr/bin/ld: XzHandler.cpp:(.text+0xd37): undefined reference to `NCompress::NXz::CEncoder::SetCoderProp(unsigned int, tagPROPVARIANT const&)'
/usr/bin/ld: XzHandler.o: in function `NArchive::NXz::CHandler::CHandler()':
XzHandler.cpp:(.text+0x2668): undefined reference to `NCompress::NXz::CStatInfo::Clear()'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::TranslateError(unsigned long)':
Lzma2Encoder.cpp:(.text+0x1a0): undefined reference to `FL2_getErrorCode'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::~FastLzma2()':
Lzma2Encoder.cpp:(.text+0x31c): undefined reference to `FL2_freeCCtx'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::SetCoderProperties(unsigned int const*, tagPROPVARIANT const*, unsigned int)':
Lzma2Encoder.cpp:(.text+0x40c): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x41e): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x466): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x46e): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x531): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x539): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x554): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x562): undefined reference to `FL2_setCStreamTimeout'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x582): undefined reference to `FL2_createCStreamMt'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x5a8): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x5bb): undefined reference to `FL2_CCtx_getParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x5d2): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x5da): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x5fd): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x605): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x627): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x62f): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x652): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x65a): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x67d): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x685): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x6a8): undefined reference to `FL2_CCtx_setParameter'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x6b0): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::GetDictSize() const':
Lzma2Encoder.cpp:(.text+0x729): undefined reference to `FL2_CCtx_getParameter'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::Begin()':
Lzma2Encoder.cpp:(.text+0x7aa): undefined reference to `FL2_initCStream'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x7b5): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x7d4): undefined reference to `FL2_getDictionaryBuffer'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x7df): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::UpdateProgress(ICompressProgressInfo*)':
Lzma2Encoder.cpp:(.text+0x831): undefined reference to `FL2_getCStreamProgress'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x862): undefined reference to `FL2_cancelCStream'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::WaitAndReport(unsigned long&, ICompressProgressInfo*)':
Lzma2Encoder.cpp:(.text+0x87f): undefined reference to `FL2_isTimedOut'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x89b): undefined reference to `FL2_waitCStream'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x8ab): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::WriteBuffers(ISequentialOutStream*)':
Lzma2Encoder.cpp:(.text+0x8e4): undefined reference to `FL2_getNextCompressedBuffer'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x8ef): undefined reference to `FL2_isTimedOut'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x8fb): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::AddByteCount(unsigned long, ISequentialOutStream*, ICompressProgressInfo*)':
Lzma2Encoder.cpp:(.text+0x975): undefined reference to `FL2_updateDictionary'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x9b4): undefined reference to `FL2_getDictionaryBuffer'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x9c3): undefined reference to `FL2_isTimedOut'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x9e1): undefined reference to `FL2_getDictionaryBuffer'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0x9f5): undefined reference to `FL2_isError'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::End(ISequentialOutStream*, ICompressProgressInfo*)':
Lzma2Encoder.cpp:(.text+0xa42): undefined reference to `FL2_updateDictionary'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0xa68): undefined reference to `FL2_endStream'
/usr/bin/ld: Lzma2Encoder.cpp:(.text+0xaa8): undefined reference to `FL2_endStream'
/usr/bin/ld: Lzma2Encoder.o: in function `NCompress::NLzma2::CFastEncoder::FastLzma2::Cancel()':
Lzma2Encoder.cpp:(.text+0xae4): undefined reference to `FL2_cancelCStream'
collect2: error: ld returned 1 exit status
make[1]: *** [../../../../makefile.glb:26: ../../../../bin/7zr] Error 1
make[1]: Leaving directory '/tmp/test/p7zip_17.02/CPP/7zip/Bundles/Alone7z'
make: *** [makefile:20: 7zr] Error 2

**Comment by BellaXlp** [comment]
@teoberiThe README says that only the 7ZA and 7Z sections have been updated.

**Comment by BellaXlp** [comment]
@teoberi 
The README says that only the 7ZA and 7Z sections have been updated.

**Comment by teoberi** [comment]
@BellaXlp you may want to refer to ChangeLog?

> Version 17.02
> =============
>   - p7zip 17.02 is more like 7zip 17.01(only 7za and 7z),The difference from 7zip 17.01 
>     and older version p7zip is the following description ....

It's a little unclear anyway.
Another problem:
`make -j 4 test`

> ...
> 7-Zip (a) [64] 17.02 : Copyright (c) 1999-2020 Igor Pavlov : 2017-08-28
> p7zip Version 17.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)
> 
> Scanning the drive for archives:
> 1 file, 205723 bytes (201 KiB)
> 
> Testing archive: ../test/7za433_rar.rar
> ERROR: ../test/7za433_rar.rar
> Can not open the file as archive
> 
> 
> Can't open as archive: 1
> Files: 0
> Size:       0
> Compressed: 0
> ERROR during : /tmp/test/p7zip_17.02/check/../bin/7za t ../test/7za433_rar.rar
> make: *** [makefile.common:101: test] Error 1

Testing for 7z is still OK.
` make -j 4 test_7z`

> Everything is Ok
> 
> Size:       462336
> Compressed: 194508
> 
> ===========
> 
> ALL SUCCESS
> 
> ===========

**Comment by jinfeihan57** [comment]
“make -j 4 test_7zr ERROR” Don't worry I will look at it later .(At the beginning I only updated 7za and 7z）

**Comment by jinfeihan57** [comment]
“make -j 4 test ERROR” this error because I added a lot of test cases in check.sh, which makes many archive formats that 7za and 7zr do not support have been added. For example: rar, "make test" actually tests 7za. So the error is report:
      ...
      ERROR: ../test/7za433_rar.rar
      Can not open the file as archive
      ...
sorry about that I will fix this error.

**Comment by teoberi** [comment]
fix 7zr compiler error from here:
https://github.com/jinfeihan57/p7zip/commit/7ac8f8d3e8a793104e887f67c021eadc419a409f
is working!

**Comment by jinfeihan57** [comment]
@teoberi 
Would it be better to open different issues for different problems?
One issue per problem, which makes it easy for others to search for the same issue.
So,Please open a new issue.

**Comment by teoberi** [comment]
https://github.com/jinfeihan57/p7zip/commit/abdfc454a4f058b864aea5e35ea5defa3c1b0138 
make -j 4 test -> OK
make -j 4 test_7z -> OK
https://github.com/szcnick/p7zip/commit/ba539b408cb93830463d9ecdf6537cf623c5270c 
make -j 4 test_7zr -> OK
All good!
