### ISSUE TITLE
p7zip-17.02 -> make -j 4 Client7z -> error 

### ISSUE THREAD

**Issue by teoberi** [szcnick/p7zip#57]
`cp makefile.linux_amd64 makefile.machine`
`make -j 4 Client7z`
output error is:
> ../../../../CPP/7zip/UI/Client7z/Client7z.cpp: In function ‘int main(int, const char**)’:
../../../../CPP/7zip/UI/Client7z/Client7z.cpp:936:58: error: invalid new-expression of abstract class type ‘CArchiveExtractCallback’
  936 |       CArchiveExtractCallback *extractCallbackSpec = new CArchiveExtractCallback;
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~
../../../../CPP/7zip/UI/Client7z/Client7z.cpp:195:7: note:   because the following virtual functions are pure within ‘CArchiveExtractCallback’:
  195 | class CArchiveExtractCallback:
      |       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../CPP/7zip/UI/Client7z/Client7z.cpp:25:
../../../../CPP/7zip/UI/Client7z/../../Archive/IArchive.h:178:16: note:         ‘virtual bool IArchiveExtractCallback::SetFileSymLinkAttrib()’
  178 |   virtual bool SetFileSymLinkAttrib() x; \
      |                ^~~~~~~~~~~~~~~~~~~~
../../../../CPP/7zip/UI/Client7z/../../Archive/IArchive.h:182:3: note: in expansion of macro ‘INTERFACE_IArchiveExtractCallback’
  182 |   INTERFACE_IArchiveExtractCallback(PURE)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [makefile.list:48: Client7z.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/test/p7zip_17.02/CPP/7zip/UI/Client7z'
make: *** [makefile:25: Client7z] Error 2

and LZHAM custom codec plugin is missing.

**Comment by jinfeihan57** [comment]
lzham is not in 7zip, it’s in 7zip-zstd. I haven't added it yet.
Do you wish to use it？？

**Comment by teoberi** [comment]
In p7zip v16.02 (original) and p7zip v17.01 I have these files:
/usr/lib64/p7zip/Lzham.so
/usr/lib64/p7zip/Codecs/Lzham.so
In p7zip v17.02 the error from the previous post appears and both files are missing.

**Comment by jinfeihan57** [comment]
I just fix Client7z.
Please open a new issue about lzham.
Thanks!

**Comment by teoberi** [comment]
If you post what fixed for Client7z, I would like to test and see how it works with lzham.
Thank you gentlemen for what you do for p7zip. I need it for Amavis and both for the Postfix mail server.
I compile p7zip for Slackware and it works even if you use Ubuntu!

**Comment by jinfeihan57** [comment]
[Client7z ](https://github.com/szcnick/p7zip/pull/58)compile OK ！

**Comment by teoberi** [comment]
All good!
Thank you.
