### ISSUE TITLE
p7zip-17.02 -> lzham is missing (not build)

### ISSUE THREAD

**Issue by teoberi** [szcnick/p7zip#59]
In p7zip v16.02 (original) and p7zip v17.01 I have these files:
/usr/lib64/p7zip/Lzham.so
/usr/lib64/p7zip/Codecs/Lzham.so
In p7zip v17.02 the error below appears and both files are missing.
 > ../../../../CPP/7zip/UI/Client7z/Client7z.cpp: In function ‘int main(int, const char**)’:
../../../../CPP/7zip/UI/Client7z/Client7z.cpp:936:58: error: invalid new-expression of abstract class type ‘CArchiveExtractCallback’
  936 |       CArchiveExtractCallback *extractCallbackSpec = new CArchiveExtractCallback;
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~
../../../../CPP/7zip/UI/Client7z/Client7z.cpp:195:7: note:   because the following virtual functions are pure within ‘CArchiveExtractCallback’:
  195 | class CArchiveExtractCallback:
      |       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../CPP/7zip/UI/Client7z/Client7z.cpp:25:
../../../../CPP/7zip/UI/Client7z/../../Archive/IArchive.h:178:16: note:         ‘virtual bool IArchiveExtractCallback::SetFileSymLinkAttrib()’
  178 |   virtual bool SetFileSymLinkAttrib() x; \
      |                ^~~~~~~~~~~~~~~~~~~~
../../../../CPP/7zip/UI/Client7z/../../Archive/IArchive.h:182:3: note: in expansion of macro ‘INTERFACE_IArchiveExtractCallback’
  182 |   INTERFACE_IArchiveExtractCallback(PURE)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [makefile.list:48: Client7z.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/test/p7zip_17.02/CPP/7zip/UI/Client7z'
make: *** [makefile:25: Client7z] Error 2

**Comment by teoberi** [comment]
After solving the problem with Client7z, the problem with lzham was solved (they were somehow related to each other, the error for Client7z interrupted the compilation).
All good!
Thank you.

**Comment by jinfeihan57** [comment]
Are SURE ？

**Comment by teoberi** [comment]
> Slackware package maker, version 3.14159265.

Searching for symbolic links:

No symbolic links were found, so we won't make an installation script.
You can make your own later in ./install/doinst.sh and rebuild the
package if you like.

This next step is optional - you can set the directories in your package
to some sane permissions. If any of the directories in your package have
special permissions, then DO NOT reset them here!

Would you like to reset all directory permissions to 755 (drwxr-xr-x) and
directory ownerships to root.root ([y]es, [n]o)? n

Creating Slackware package:  /tmp/p7zip-17.02-x86_64-1alien.tgz

./
install/
install/doinst.sh
install/slack-desc
install/slack-required
usr/
usr/bin/
usr/bin/7z
usr/bin/7za
usr/bin/7zr
usr/bin/p7zip
usr/doc/
usr/doc/p7zip-17.02/
usr/doc/p7zip-17.02/7zC.txt
usr/doc/p7zip-17.02/7zFormat.txt
usr/doc/p7zip-17.02/ChangeLog
usr/doc/p7zip-17.02/License.txt
usr/doc/p7zip-17.02/Methods.txt
usr/doc/p7zip-17.02/README
usr/doc/p7zip-17.02/README.md
usr/doc/p7zip-17.02/README.p7zip_wrapper
usr/doc/p7zip-17.02/Struct.EAP
usr/doc/p7zip-17.02/Struct.ldb
usr/doc/p7zip-17.02/TODO
usr/doc/p7zip-17.02/copying.txt
usr/doc/p7zip-17.02/lzma.txt
usr/doc/p7zip-17.02/p7zip.SlackBuild
usr/doc/p7zip-17.02/readme.txt
usr/doc/p7zip-17.02/src-history.txt
usr/doc/p7zip-17.02/unRarLicense.txt
usr/lib64/
usr/lib64/p7zip/
usr/lib64/p7zip/7z
usr/lib64/p7zip/7z.so
usr/lib64/p7zip/7zCon.sfx
usr/lib64/p7zip/7za
usr/lib64/p7zip/7zr
usr/lib64/p7zip/Codecs/
usr/lib64/p7zip/Codecs/Lzham.so
usr/lib64/p7zip/Codecs/Rar.so
usr/lib64/p7zip/Lzham.so
usr/lib64/p7zip/Rar.so
usr/man/
usr/man/man1/
usr/man/man1/7z.1.gz
usr/man/man1/7za.1.gz
usr/man/man1/7zr.1.gz
usr/man/man1/p7zip.1.gz

Slackware package /tmp/p7zip-17.02-x86_64-1alien.tgz created.
