### ISSUE TITLE
Build error on Haiku 

### ISSUE THREAD

**Issue by Coldfirex** [szcnick/p7zip#62]
Howdy,
It's possible this is a Haiku side issue, but I got the following build error trying to compile it today.
[Screenshot](https://imgur.com/OVS3QrB)
I see there is a make file already for Haiku in the directory, do I need to do anything with it?
Complete newb at this.

Git clone as of 7/11/2020 on Haiku R1 Nightly (7/11/2020).

**Comment by jinfeihan57** [comment]
try this :
" cp makefile.haiku makefile.machine
  make 7z && make 7za && make 7zr "

**Comment by Coldfirex** [comment]
That worked, thanks!
