### ISSUE TITLE
[patch] Implement proper code page selection for OEM archives

### ISSUE THREAD

**Issue by unxed** [szcnick/p7zip#63]
https://sourceforge.net/p/p7zip/bugs/187/#816e

Original discussion: https://github.com/mate-desktop/engrampa/issues/5

**Comment by jinfeihan57** [comment]
Can you provide a PR?

**Comment by unxed** [comment]
> Can you provide a PR?

https://github.com/szcnick/p7zip/pull/64

**Comment by jinfeihan57** [comment]
It's been merged，thanks.

**Comment by jinfeihan57** [comment]
Compilation error on cygwin.

**Comment by unxed** [comment]
@jinfeihan57 got no windows. Сan you please provide an error log?

**Comment by jinfeihan57** [comment]
![截图](https://user-images.githubusercontent.com/38484902/88125823-aea0dc00-cc02-11ea-82f6-17265f8a03c8.PNG)
[I added the compilation conditions. ](https://github.com/jinfeihan57/p7zip/commit/0e0a1a8316b691de8f1eca8e9520274e00205884?diff=unified)

**Comment by unxed** [comment]
Looks like this package is missing in cygwin installation:
http://www.cygwin.com/packages/summary/libiconv-devel.html

**Comment by jinfeihan57** [comment]
Actually I do insatll [libiconv-debuginfo](https://www.cygwin.com/packages/summary/libiconv-debuginfo.html).
I don't know why libiconv-debuginfo not work. But I will try libiconv-devel later.

**Comment by jinfeihan57** [comment]
![截图](https://user-images.githubusercontent.com/38484902/88259547-16cfea80-ccf5-11ea-8c03-eff075be2704.PNG)
I installed libiconv-devel on cygwin, But it still won't work. same ERROR.

**Comment by unxed** [comment]
Can't digg within this as I have no windows installed. Maybe we can add conditional compilation rules to skip this part under cygwin for now?

**Comment by jinfeihan57** [comment]
I already fixed it. check #68 .
