### ISSUE TITLE
segfault : .xz LZMA2:26 CRC64

### ISSUE THREAD

**Issue by biopsin** [szcnick/p7zip#66]
Hi, 
anyone get segfault while extracting a .xz with method=LZMA2:26 CRC64
Extracts fine with xz v.5.2.5..

**Comment by jinfeihan57** [comment]
can you upload a test file?

**Comment by biopsin** [comment]
Yup, it's this file uploaded by someone
https://github.com/xanmod/linux/releases/download/5.4.62-xanmod1/patch-5.4.62-xanmod1.xz

**Comment by biopsin** [comment]
I'm building this on voidlinux_x86_64_glib, I only build 7z and omit 7za & 7zr.

**Comment by jinfeihan57** [comment]
> I'm building this on voidlinux_x86_64_glib, I only build 7z and omit 7za & 7zr.

It OK，to not build 7za and 7zr.

**Comment by jinfeihan57** [comment]
@biopsin 
I submitted a PR on dev branch. Please test it.

**Comment by biopsin** [comment]
tested and working, much oblige mister
