### ISSUE TITLE
Alpine Linux warning

### ISSUE THREAD

**Issue by alicektx** [szcnick/p7zip#75]
Stumbled upon this warning under Alpine which uses musl instead of glibc:

`gcc -c -I. -I../../../../C -I../../../../CPP/myWindows -I../../../../CPP/include_windows -I../../../../CPP -O -s -pipe -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG -D_REENTRANT -DENV_UNIX -D_7ZIP_LARGE_PAGES  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -DENV_UNIX -DBREAK_HANDLER -DUNICODE -D_UNICODE -DUNIX_USE_WIN_FILE -DZSTD_MULTITHREAD -DNO_XXHASH -DFL2_7ZIP_BUILD   ../../../../C/Threads.c
../../../../C/Threads.c:15: warning: "PTHREAD_MUTEX_ERRORCHECK" redefined
   15 | #define PTHREAD_MUTEX_ERRORCHECK PTHREAD_MUTEX_ERRORCHECK_NP
      | 
In file included from ../../../../C/Threads.h:14,
                 from ../../../../C/Threads.c:3:
/usr/include/pthread.h:39: note: this is the location of the previous definition
   39 | #define PTHREAD_MUTEX_ERRORCHECK 2`

musl appears to not support for PTHREAD_MUTEX_ERRORCHECK_NP:
https://git.musl-libc.org/cgit/musl/tree/include/pthread.h

(not really a C programmer myself, but) The following quick'n'dirty 'fix' in Threads.c, appears to have taken care of such:
```
#if defined(__linux__) && defined(__GLIBC__)
#define PTHREAD_MUTEX_ERRORCHECK PTHREAD_MUTEX_ERRORCHECK_NP
#endif
```
All the best

**Comment by jinfeihan57** [comment]
Have you test it? AND
Can you submit a PR? 
Thanks!

**Comment by alicektx** [comment]
Thank you!
