### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by joshcangit** [szcnick/p7zip#76]
I'm not sure how to compress to 7z with FastLZMA2. It seems to use LZMA2.

Also, for compression level of FastLZMA2, I wonder if Fast is best or I should use Normal or maybe Maximum or even Ultra? I'm looking for fastest decompression.

**Comment by jinfeihan57** [comment]
./7z a archive.7z filename -m0=flzma2 -mx9
These parameters will use fastlzma2  level 9 compressed files.
Fastlzma2 is fully compatible with lzma2. So they share the decompression algorithm.
If you want to decompress faster, try zstd & lz4 compression algorithm.

**Comment by joshcangit** [comment]
So, Maximum compression level is ideal right?

Much thanks.

Also, yes I've tried zstd and lz4 and we're indeed very fast but they didn't work for `.cb7` files.
I'm sure comic book readers only use default codecs.
Forgot to tell you this was what I was looking for.

**Comment by jinfeihan57** [comment]
Use Maximum compression level to obtain the maximum compression ratio and make the compression speed slowest.
