### ISSUE TITLE
Mac: 7za b -mmt=* -mm=* benchmark fails with ERROR decoding CRC64

### ISSUE THREAD

**Issue by ApexMods** [szcnick/p7zip#78]
This happens on all machines I tested on, so it’s not caused by faulty hardware.

Aside from this error, there is no documentation whatsoever on FLZMA2 support, i.e. how to use it. Setting m0=flmza2 seems to work, but there are no speed or memory usage differences at all.

During compilation on Mac x64 gcc, there are a couple of clang “linker” input unused command line arguments for core foundation in the FLZMA2 part.

**Comment by jinfeihan57** [comment]
Check the following  issues and PRs ：
#66 #69，#56 #58 

How to use flzma2 ?
    ./7za a t.7z filepath -m0=flzma2

**Comment by ApexMods** [comment]
I have used -m0=flzma2, but there is no noticeable speed increase or reduced memory usage at -mx9 (with 16-core / -mmt16) over using -m0=lzma2.

**Comment by ApexMods** [comment]
The current dev branch won’t build on Mac at all (undefined symbols for x86_64), so I cannot check any fixes in dev.

**Comment by jinfeihan57** [comment]
@ApexMods 
Can you give me all the wrong information?

**Comment by ApexMods** [comment]
Issue is in /CPP/7zip/Archive/Zip/ZipItem.cpp

#include <iconv.h>

iconv_open, iconv_close

**Comment by ApexMods** [comment]
Got it to compile by replacing ZipItem.cpp with the one from the release.  FLZMA2 works now, and it’s great. =)
