### ISSUE TITLE
Update CMakeLists.txt

### ISSUE THREAD

**Issue by TheOneRing** [szcnick/p7zip#79]
KDE Craft currently uses the old p7zip.
As the project is cross platform we had the best experience with the cmake build system.

In this fork the cmake support is outdated but the hand written makefiles are still maintained.
How about switching to cmake which would, after some initial effort, probably simplify development.

**Comment by TheOneRing** [comment]
If cmake is out of scope I vote for a removal of the unmaintained scripts

**Comment by jinfeihan57** [comment]
I will update cmake next week.  ; )

**Comment by jinfeihan57** [comment]
#80 
Note:  The RAR format and SFX mode are not supported in cmake build.

**Comment by jinfeihan57** [comment]
@TheOneRing
Check the latest dev branch.

**Comment by TheOneRing** [comment]
thx 😄
