### ISSUE TITLE
compile p7zip-17.02 fail under gcc 4.8.5, but compile  p7zip_16.02 success under gcc 4.8.5

### ISSUE THREAD

**Issue by l1t1** [szcnick/p7zip#89]
# make 7za -j -s
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_createCCtx_internal’:
../../../../C/fast-lzma2/fl2_compress.c:149:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned u = 0; u < nbThreads; ++u)
     ^
../../../../C/fast-lzma2/fl2_compress.c:149:5: note: use option -std=c99 or -std=gnu99 to compile your code
../../../../C/fast-lzma2/fl2_compress.c:172:19: error: redefinition of ‘u’
     for (unsigned u = 0; u < nbThreads; ++u) {
                   ^
../../../../C/fast-lzma2/fl2_compress.c:149:19: note: previous definition of ‘u’ was here
     for (unsigned u = 0; u < nbThreads; ++u)
                   ^
../../../../C/fast-lzma2/fl2_compress.c:172:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned u = 0; u < nbThreads; ++u) {
     ^
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_freeCCtx’:
../../../../C/fast-lzma2/fl2_compress.c:208:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned u = 0; u < cctx->jobCount; ++u) {
     ^
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_initEncoders’:
../../../../C/fast-lzma2/fl2_compress.c:248:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(unsigned u = 0; u < cctx->jobCount; ++u) {
     ^
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_compressCurBlock_blocking’:
../../../../C/fast-lzma2/fl2_compress.c:288:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t u = 1; u < nbThreads; ++u) {
     ^
../../../../C/fast-lzma2/fl2_compress.c:352:17: error: redefinition of ‘u’
     for (size_t u = 0; u < nbThreads; ++u)
                 ^
../../../../C/fast-lzma2/fl2_compress.c:288:17: note: previous definition of ‘u’ was here
     for (size_t u = 1; u < nbThreads; ++u) {
                 ^
../../../../C/fast-lzma2/fl2_compress.c:352:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t u = 0; u < nbThreads; ++u)
     ^
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_compressBuffer’:
../../../../C/fast-lzma2/fl2_compress.c:512:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t u = 0; u < cctx->threadCount; ++u) {
         ^
../../../../C/fast-lzma2/fl2_compress.c: In function ‘FL2_remainingOutputSize’:
../../../../C/fast-lzma2/fl2_compress.c:1124:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t u = fcs->outThread; u < fcs->threadCount; ++u)
     ^
make[1]: *** [fl2_compress.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../../../../C/fast-lzma2/fl2_pool.c: In function ‘FL2POOL_join’:
../../../../C/fast-lzma2/fl2_pool.c:131:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < ctx->numThreads; ++i)
     ^
../../../../C/fast-lzma2/fl2_pool.c:131:5: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [fl2_pool.o] Error 1
In file included from ../../../../C/fast-lzma2/lzma2_enc.c:17:0:
../../../../C/fast-lzma2/range_enc.h: In function ‘RC_flush’:
../../../../C/fast-lzma2/range_enc.h:154:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < 5; ++i)
     ^
../../../../C/fast-lzma2/range_enc.h:154:5: note: use option -std=c99 or -std=gnu99 to compile your code
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_lengthStates_SetPrices’:
../../../../C/fast-lzma2/lzma2_enc.c:384:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < 8; i += 2) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_lengthStates_updatePrices’:
../../../../C/fast-lzma2/lzma2_enc.c:404:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t pos_state = 0; pos_state <= enc->pos_mask; pos_state++) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c:435:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t pos_state = 1; pos_state <= enc->pos_mask; pos_state++)
         ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_encodeChunkFast’:
../../../../C/fast-lzma2/lzma2_enc.c:650:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t next = pos + 1; best_match.length < kMatchLenMax && next < uncompressed_end; ++next) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_optimalParse’:
../../../../C/fast-lzma2/lzma2_enc.c:1082:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t rep_index = 0; rep_index < kNumReps; ++rep_index) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_initMatchesPos0Best’:
../../../../C/fast-lzma2/lzma2_enc.c:1313:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (ptrdiff_t match_index = enc->match_count - 1; match_index >= start_match; --match_index) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_initOptimizerPos0’:
../../../../C/fast-lzma2/lzma2_enc.c:1362:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumReps; ++i) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1410:17: error: redefinition of ‘i’
     for (size_t i = 0; i < kNumReps; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1362:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < kNumReps; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1410:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumReps; ++i) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_encodeOptimumSequence’:
../../../../C/fast-lzma2/lzma2_enc.c:1483:21: error: ‘for’ loop initial declarations are only allowed in C99 mode
                     for (size_t j = cur + 1; j <= len_end; j++) {
                     ^
../../../../C/fast-lzma2/lzma2_enc.c:1497:17: error: ‘for’ loop initial declarations are only allowed in C99 mode
                 for (size_t j = cur + 1; j <= end; j++) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_fillDistancesPrices’:
../../../../C/fast-lzma2/lzma2_enc.c:1579:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = kStartPosModelIndex / 2; i < kNumFullDistances / 2; i++) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1603:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned lps = 0; lps < kNumLenToPosStates; lps++) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1641:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (size_t i = 4; i < kNumFullDistances; i += 2) {
             ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_lengthStates_Reset’:
../../../../C/fast-lzma2/lzma2_enc.c:1703:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < (kNumPositionStatesMax << (kLenNumLowBits + 1)); ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1706:17: error: redefinition of ‘i’
     for (size_t i = 0; i < kLenNumHighSymbols; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1703:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < (kNumPositionStatesMax << (kLenNumLowBits + 1)); ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1706:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kLenNumHighSymbols; ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA_encoderStates_Reset’:
../../../../C/fast-lzma2/lzma2_enc.c:1716:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumReps; ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1719:17: error: redefinition of ‘i’
     for (size_t i = 0; i < kNumStates; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1716:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < kNumReps; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1719:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumStates; ++i) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1720:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t j = 0; j < kNumPositionStatesMax; ++j) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c:1730:17: error: redefinition of ‘i’
     for (size_t i = 0; i < num; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1719:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < kNumStates; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1730:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < num; ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1733:17: error: redefinition of ‘i’
     for (size_t i = 0; i < kNumLenToPosStates; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1730:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < num; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1733:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumLenToPosStates; ++i) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1735:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t j = 0; j < (1 << kNumPosSlotBits); ++j)
         ^
../../../../C/fast-lzma2/lzma2_enc.c:1738:17: error: redefinition of ‘i’
     for (size_t i = 0; i < kNumFullDistances - kEndPosModelIndex; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1733:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < kNumLenToPosStates; ++i) {
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1738:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < kNumFullDistances - kEndPosModelIndex; ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c:1744:17: error: redefinition of ‘i’
     for (size_t i = 0; i < (1 << kNumAlignBits); ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1738:17: note: previous definition of ‘i’ was here
     for (size_t i = 0; i < kNumFullDistances - kEndPosModelIndex; ++i)
                 ^
../../../../C/fast-lzma2/lzma2_enc.c:1744:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < (1 << kNumAlignBits); ++i)
     ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA2_getDictSizeProp’:
../../../../C/fast-lzma2/lzma2_enc.c:1751:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (BYTE bit = 11; bit < 32; ++bit) {
     ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA2_isChunkIncompressible’:
../../../../C/fast-lzma2/lzma2_enc.c:1840:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
    for (size_t pos = start; pos < end; ) {
    ^
../../../../C/fast-lzma2/lzma2_enc.c:1867:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
    for (size_t pos = start; pos < end; ) {
    ^
../../../../C/fast-lzma2/lzma2_enc.c:1895:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t pos = start; pos < end; ++pos)
         ^
../../../../C/fast-lzma2/lzma2_enc.c:1898:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t i = 0; i < 256; ++i) {
         ^
../../../../C/fast-lzma2/lzma2_enc.c: In function ‘LZMA2_encode’:
../../../../C/fast-lzma2/lzma2_enc.c:1990:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t pos = start; pos < block.end;) {
     ^
make[1]: *** [lzma2_enc.o] Error 1

make: *** [7za] Error 2

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by l1t1** [comment]
#  make 7za -j -s CC="gcc -std=c99 "
In file included from ../../../../C/fast-lzma2/fl2_compress_internal.h:23:0,
                 from ../../../../C/fast-lzma2/fl2_compress.c:19:
../../../../C/fast-lzma2/fl2_threading.h:121:30: warning: ‘struct timespec’ declared inside parameter list [enabled by default]
 mythread_condtime_set(struct timespec *condtime, U32 timeout_ms)
                              ^
../../../../C/fast-lzma2/fl2_threading.h: In function ‘mythread_condtime_set’:
../../../../C/fast-lzma2/fl2_threading.h:123:10: error: dereferencing pointer to incomplete type
  condtime->tv_sec = timeout_ms / 1000;
          ^
../../../../C/fast-lzma2/fl2_threading.h:124:10: error: dereferencing pointer to incomplete type
  condtime->tv_nsec = (timeout_ms % 1000) * 1000000;
          ^
../../../../C/fast-lzma2/fl2_threading.h:129:10: error: dereferencing pointer to incomplete type
  condtime->tv_sec += now.tv_sec;
          ^
../../../../C/fast-lzma2/fl2_threading.h:130:10: error: dereferencing pointer to incomplete type
  condtime->tv_nsec += now.tv_usec * 1000L;
          ^
../../../../C/fast-lzma2/fl2_threading.h:133:14: error: dereferencing pointer to incomplete type
  if (condtime->tv_nsec >= 1000000000L) {
              ^
../../../../C/fast-lzma2/fl2_threading.h:134:11: error: dereferencing pointer to incomplete type
   condtime->tv_nsec -= 1000000000L;
           ^
../../../../C/fast-lzma2/fl2_threading.h:135:13: error: dereferencing pointer to incomplete type
   ++condtime->tv_sec;
             ^
../../../../C/fast-lzma2/fl2_threading.h: In function ‘FL2_pthread_cond_timedwait’:
../../../../C/fast-lzma2/fl2_threading.h:146:21: error: storage size of ‘condtime’ isn’t known
     struct timespec condtime;
                     ^
make[1]: *** [fl2_compress.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [7za] Error 2

**Comment by l1t1** [comment]
make -j -s  CC="gcc -std=c11" success

**Comment by jinfeihan57** [comment]
You can also try :
make -j -s CC="gcc -std=gnu99"
